sudo: false
public: trusty
language: node_js

services:
  - docker

cache:
  directories:
    - node_modules

node_js:
  - "7"
  - "8"
  - "node"

before_install:
  - npm install npm@5 -g
  - npm cache verify
  - npm update

install:
  - npm install

after_success:
  -docker --version
  

script:
  - npm run ci:travis
