sudo: false
public: trusty
language: node_js

cache:
  directories:
    - node_modules

node_js:
  - "7"
  - "8"
  - "node"

before_install:
  - npm install npm@5 -g
  - npm cache verify
  - npm prune
  - npm update

install:
  - npm install

script:
  - npm run ci:travis
